#!/usr/bin/env node

/**
 * OAuth Setup Helper
 *
 * Interactive script to help configure OAuth 2.0 for MCP Proxy.
 * Run: node .validation/setup-oauth.js
 *
 * This script will:
 * 1. Check for existing .env file
 * 2. Prompt for OAuth credentials
 * 3. Generate a SESSION_SECRET if needed
 * 4. Update .env file with credentials
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import crypto from 'crypto';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const colors = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  blue: '\x1b[36m',
  bold: '\x1b[1m',
  dim: '\x1b[2m'
};

const log = {
  info: (msg) => console.log(`${colors.blue}[INFO]${colors.reset} ${msg}`),
  success: (msg) => console.log(`${colors.green}[✓]${colors.reset} ${msg}`),
  error: (msg) => console.log(`${colors.red}[✗]${colors.reset} ${msg}`),
  warn: (msg) => console.log(`${colors.yellow}[!]${colors.reset} ${msg}`),
  header: (msg) => console.log(`\n${colors.bold}${colors.blue}${msg}${colors.reset}`),
  dim: (msg) => console.log(`${colors.dim}${msg}${colors.reset}`)
};

// Generate a random session secret
const generateSessionSecret = () => {
  return crypto.randomBytes(32).toString('base64');
};

// Read .env file
const readEnv = () => {
  const envPath = path.join(__dirname, '..', '.env');
  if (fs.existsSync(envPath)) {
    return fs.readFileSync(envPath, 'utf-8');
  }
  return '';
};

// Write .env file
const writeEnv = (content) => {
  const envPath = path.join(__dirname, '..', '.env');
  fs.writeFileSync(envPath, content);
};

// Prompt user for input (basic implementation)
const prompt = (question) => {
  return new Promise((resolve) => {
    process.stdout.write(`${colors.blue}?${colors.reset} ${question} `);
    process.stdin.once('data', (data) => {
      resolve(data.toString().trim());
    });
  });
};

// Main setup flow
const setupOAuth = async () => {
  console.log('\n╔═══════════════════════════════════════════════════════════╗');
  console.log('║  MCP Proxy OAuth 2.0 Setup Helper                         ║');
  console.log('╚═══════════════════════════════════════════════════════════╝\n');

  const existingEnv = readEnv();
  let envContent = existingEnv;

  // Check if .env exists
  if (existingEnv) {
    log.success('Found existing .env file');
    log.info('Current values will be preserved if you press Enter without typing');
  } else {
    log.info('Creating new .env file');
    // Add header to new .env
    envContent = '# MCP Proxy Environment Variables\n# Generated by setup-oauth.js\n\n';
  }

  console.log('\n' + '='.repeat(60));
  log.header('Step 1: GitHub OAuth Configuration');
  log.dim('If you haven\'t created a GitHub OAuth app yet:');
  log.dim('1. Go to https://github.com/settings/developers');
  log.dim('2. Click "New OAuth App"');
  log.dim('3. Set Homepage URL: http://127.0.0.1:8080');
  log.dim('4. Set Callback URL: http://127.0.0.1:8080/auth/callback');
  console.log('='.repeat(60) + '\n');

  // Get GitHub Client ID
  const currentClientId = envContent.match(/GITHUB_CLIENT_ID=(.+)/)?.[1] || '';
  const clientId = await prompt(`GitHub Client ID${currentClientId ? ` [${currentClientId}]` : ''}:`);
  if (clientId) {
    // Update or add GITHUB_CLIENT_ID
    if (envContent.includes('GITHUB_CLIENT_ID=')) {
      envContent = envContent.replace(/GITHUB_CLIENT_ID=.+/, `GITHUB_CLIENT_ID=${clientId}`);
    } else {
      envContent += `\nGITHUB_CLIENT_ID=${clientId}`;
    }
  }

  // Get GitHub Client Secret
  const currentSecret = envContent.match(/GITHUB_CLIENT_SECRET=(.+)/)?.[1] || '';
  const clientSecret = await prompt(`GitHub Client Secret${currentSecret ? ' [***hidden***]' : ''}:`);
  if (clientSecret) {
    if (envContent.includes('GITHUB_CLIENT_SECRET=')) {
      envContent = envContent.replace(/GITHUB_CLIENT_SECRET=.+/, `GITHUB_CLIENT_SECRET=${clientSecret}`);
    } else {
      envContent += `\nGITHUB_CLIENT_SECRET=${clientSecret}`;
    }
  }

  console.log('\n' + '='.repeat(60));
  log.header('Step 2: Session Secret');
  log.dim('This is used to encrypt session cookies.');
  log.dim('Leave empty to generate a random secret.');
  console.log('='.repeat(60) + '\n');

  // Get or generate SESSION_SECRET
  const currentSessionSecret = envContent.match(/SESSION_SECRET=(.+)/)?.[1] || '';
  let sessionSecret = await prompt(`Session Secret${currentSessionSecret ? ' [***hidden***]' : ' (press Enter to generate)'}:`);

  if (!sessionSecret && !currentSessionSecret) {
    sessionSecret = generateSessionSecret();
    log.success(`Generated session secret: ${sessionSecret.substring(0, 10)}...`);
  }

  if (sessionSecret) {
    if (envContent.includes('SESSION_SECRET=')) {
      envContent = envContent.replace(/SESSION_SECRET=.+/, `SESSION_SECRET=${sessionSecret}`);
    } else {
      envContent += `\nSESSION_SECRET=${sessionSecret}`;
    }
  }

  console.log('\n' + '='.repeat(60));
  log.header('Step 3: Optional User Restrictions');
  log.dim('You can restrict access to specific email addresses.');
  log.dim('Leave empty to allow any authenticated GitHub user.');
  console.log('='.repeat(60) + '\n');

  // Optional: Allowed users
  const allowedUsers = await prompt('Allowed email addresses (comma-separated, or empty for any):');
  if (allowedUsers) {
    const users = allowedUsers.split(',').map(u => u.trim()).filter(u => u);
    log.info(`Allowed users: ${users.join(', ')}`);
  }

  console.log('\n' + '='.repeat(60));
  log.header('Step 4: Save Configuration');
  console.log('='.repeat(60) + '\n');

  // Write the .env file
  writeEnv(envContent);

  log.success('Configuration saved to .env file');

  console.log('\n' + '─'.repeat(60));
  log.header('Next Steps:');
  console.log('─'.repeat(60));
  console.log('');
  log.info('1. Test your configuration:');
  console.log('      npm run test:oauth');
  console.log('');
  log.info('2. Start the proxy with OAuth:');
  console.log('      cd packages/mcp-http-proxy');
  console.log('      node src/cli.js -c ../examples/oauth-github.config.js');
  console.log('');
  log.info('3. Open in browser:');
  console.log('      http://127.0.0.1:8080/auth/login');
  console.log('');
  log.info('4. For full testing guide, see:');
  console.log('      .validation/END_TO_END_TESTING.md');
  console.log('');

  // Show the sensitive values warning
  log.warn('IMPORTANT: Never commit your .env file to version control!');
  log.dim('The .env file is already in .gitignore\n');
};

// Handle stdin for interactive prompts
process.stdin.setEncoding('utf8');
process.stdin.resume();

setupOAuth()
  .then(() => {
    process.exit(0);
  })
  .catch((err) => {
    log.error(`Setup failed: ${err.message}`);
    process.exit(1);
  });
